version: "3"
services:
  node-app:
    build: .
    ports: 
      - "3003:3003"
    volumes:
      - ./:/index.js
      # - /app/node_modules
    # enviroment:
    #   - PORT=3003
    env_file:
      - ./.env
